import type { Project } from "@/lib/site-data";

export const archiveProjects: Omit<Project, "number">[] = [
  {
    slug: "2d-hindi-cartoon-video",
    title: "2D Hindi Cartoon Engine",
    tagline: "A story idea into a Hindi cartoon.",
    summary: "Turns a story idea into a dialogue-based 2D cartoon: script, characters, scenes, Hindi voiceover, and YouTube packaging.",
    story: [
      "Turns a story idea into a dialogue-based 2D cartoon: script, characters, scenes, Hindi voiceover, and YouTube packaging.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["tools"],
    featured: false,
    stack: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/swapagrawal14/2d-hindi-cartoon-video",
    live: "https://swapagrawal14.github.io/2d-hindi-cartoon-video/",
    cover: "rings",
  },
  {
    slug: "3d-game-playground",
    title: "3D Game Playground",
    tagline: "Test 3D scenes in the browser.",
    summary: "A free playground for testing and building 3D game scenes in p5 — no install, just a tab.",
    story: [
      "A free playground for testing and building 3D game scenes in p5 — no install, just a tab.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["3d", "games"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/3d-game-playground",
    live: "https://3d-game-playground.vercel.app/",
    cover: "chat",
  },
  {
    slug: "3d-world-crafter",
    title: "3D World Crafter",
    tagline: "Build a world from scratch with an LLM.",
    summary: "A crafter for assembling 3D worlds from the ground up, directed by the language model of your choice.",
    story: [
      "A crafter for assembling 3D worlds from the ground up, directed by the language model of your choice.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["3d", "ai"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/3d-world-crafter",
    cover: "cube",
  },
  {
    slug: "ai-3d-models-animator",
    title: "AI 3D Model Animator",
    tagline: "Upload a model. Add motion.",
    summary: "Load a 3D file or a link and add custom animation with AI — preview in the browser, export when it feels right.",
    story: [
      "Load a 3D file or a link and add custom animation with AI — preview in the browser, export when it feels right.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["3d", "ai"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/ai-3d-models-animator",
    live: "https://ai-3d-models-animator.vercel.app",
    cover: "topo",
  },
  {
    slug: "ai-models-altogether",
    title: "All Models, One Chat",
    tagline: "Any provider, one thread.",
    summary: "Chat with models from multiple providers in a single client — pick the endpoint, keep the conversation.",
    story: [
      "Chat with models from multiple providers in a single client — pick the endpoint, keep the conversation.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai", "web"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/ai-models-altogether",
    cover: "film",
  },
  {
    slug: "ai-webapp-builder",
    title: "AI Webapp Builder",
    tagline: "Vanilla HTML, unusual products.",
    summary: "A builder specializing in unique, interactive web projects using vanilla HTML, CSS, and JavaScript.",
    story: [
      "A builder specializing in unique, interactive web projects using vanilla HTML, CSS, and JavaScript.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai", "tools", "web"],
    featured: false,
    stack: ["JavaScript", "React"],
    repo: "https://github.com/swapagrawal14/ai-webapp-builder",
    live: "https://ai-webapp-builder.vercel.app",
    cover: "brackets",
  },
  {
    slug: "ai-webapp-builder-ft-agentrouter",
    title: "Webapp Builder · AgentRouter",
    tagline: "The builder, with an agent in the loop.",
    summary: "A variant of the AI webapp builder wired through AgentRouter — same product instinct, a different routing layer.",
    story: [
      "A variant of the AI webapp builder wired through AgentRouter — same product instinct, a different routing layer.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai", "web"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/AI-webapp-builder-ft-agentrouter",
    cover: "wave",
  },
  {
    slug: "ai-webapp-builder-ft-babel-town",
    title: "Webapp Builder · Babel Town",
    tagline: "The builder, Babel Town edition.",
    summary: "Another pass at the AI webapp builder, this time through Babel Town — same brief, a different generation path.",
    story: [
      "Another pass at the AI webapp builder, this time through Babel Town — same brief, a different generation path.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["games", "ai", "web"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/AI-webapp-builder-ft-babel-town",
    cover: "orbit",
  },
  {
    slug: "ani-doc-studio-dent",
    title: "Ani Doc Studio Dent",
    tagline: "Documentary-style films for dentistry.",
    summary: "A studio for documentary-style videos when the subject is dentistry — structure, stills, and motion in one workflow.",
    story: [
      "A studio for documentary-style videos when the subject is dentistry — structure, stills, and motion in one workflow.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["dental", "tools"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/ani-doc-studio-dent",
    cover: "grid",
  },
  {
    slug: "animations-with-claude-sonnet",
    title: "Claude Sonnet Animations",
    tagline: "Prompted motion, LM Arena notes.",
    summary: "A sketchbook of animations prompted with Claude Sonnet — tests, comparisons, and the prompts that survived.",
    story: [
      "A sketchbook of animations prompted with Claude Sonnet — tests, comparisons, and the prompts that survived.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["games", "ai"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/animations-with-claude-sonnet",
    cover: "planes",
  },
  {
    slug: "art-fluent-studio",
    title: "Art Fluent Studio",
    tagline: "A small studio for fluent image work.",
    summary: "An image studio experiment — generate, iterate, and keep the interface out of the way of the picture.",
    story: [
      "An image studio experiment — generate, iterate, and keep the interface out of the way of the picture.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["tools"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/art-fluent-studio",
    cover: "badge",
  },
  {
    slug: "atlas-architect-live",
    title: "Atlas Architect",
    tagline: "A toolkit for building worlds.",
    summary: "A professional world-building toolkit for people who want to design a place, not just describe one.",
    story: [
      "A professional world-building toolkit for people who want to design a place, not just describe one.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["games", "tools"],
    featured: false,
    stack: ["JavaScript", "React"],
    repo: "https://github.com/swapagrawal14/atlas-architect-live",
    cover: "rings",
  },
  {
    slug: "basic-3d-models-generator",
    title: "Basic 3D Models Generator",
    tagline: "Text or image, in, a model out.",
    summary: "Generate simple 3D models from a sentence or a picture. Free to try, built for the first useful mesh, not the last render.",
    story: [
      "Generate simple 3D models from a sentence or a picture. Free to try, built for the first useful mesh, not the last render.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["3d", "tools"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/basic-3d-models-generator",
    live: "https://basic-3d-models-generator.vercel.app",
    cover: "chat",
  },
  {
    slug: "brainrot-shooter-game",
    title: "Brainrot Shooter",
    tagline: "A browser shooter. Play it now.",
    summary: "A fast browser shooter that runs on desktop and, in desktop mode, on a phone. Built to be played, not explained.",
    story: [
      "A fast browser shooter that runs on desktop and, in desktop mode, on a phone. Built to be played, not explained.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["games", "ai"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/Brainrot-shooter-game",
    cover: "cube",
  },
  {
    slug: "chatbots-with-api",
    title: "Chatbots with API",
    tagline: "Multi-provider chat, production-shaped.",
    summary: "A chatbot client that talks to AI models from multiple providers — one interface, several backends.",
    story: [
      "A chatbot client that talks to AI models from multiple providers — one interface, several backends.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai", "web"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/chatbots-with-api",
    live: "https://chatbots-with-api-i3bn.vercel.app",
    cover: "topo",
  },
  {
    slug: "chatbots-with-api-v2",
    title: "Chatbots with API v2",
    tagline: "The second pass at multi-model chat.",
    summary: "Version two of the multi-provider chatbot — cleaner routing, the same idea: one thread, many models.",
    story: [
      "Version two of the multi-provider chatbot — cleaner routing, the same idea: one thread, many models.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/chatbots-with-api-v2",
    live: "https://chatbots-with-api-v2.vercel.app",
    cover: "film",
  },
  {
    slug: "chatopia-swap-says",
    title: "Chatopia",
    tagline: "A conversational playground.",
    summary: "A chat experiment — a place to try voices, models, and the tone of a conversation as a product.",
    story: [
      "A chat experiment — a place to try voices, models, and the tone of a conversation as a product.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/chatopia-swap-says",
    cover: "brackets",
  },
  {
    slug: "claymation-style-videos",
    title: "Claymation Dentistry Videos",
    tagline: "Two-minute clay films for the clinic.",
    summary: "A claymation workflow for short dentistry films — Gemini avatars, Seedance, and a reference library for the style.",
    story: [
      "A claymation workflow for short dentistry films — Gemini avatars, Seedance, and a reference library for the style.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["dental", "ai", "tools"],
    featured: false,
    stack: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/swapagrawal14/claymation-style-videos",
    cover: "wave",
  },
  {
    slug: "cloudflare-workers-ai-chatbot",
    title: "Cloudflare Workers Chat",
    tagline: "Workers AI, called directly.",
    summary: "A chat client that talks to Cloudflare Workers AI via API and account id — no extra SaaS in the middle.",
    story: [
      "A chat client that talks to Cloudflare Workers AI via API and account id — no extra SaaS in the middle.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/Cloudflare-workers-ai-chatbot",
    cover: "orbit",
  },
  {
    slug: "creature-fusion-lab",
    title: "Creature Fusion Lab",
    tagline: "Combine two beings. Keep the best parts.",
    summary: "A lab for fusing creatures — prompt, combine, and see what the model invents when two references share a body.",
    story: [
      "A lab for fusing creatures — prompt, combine, and see what the model invents when two references share a body.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["web"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/creature-fusion-lab",
    cover: "grid",
  },
  {
    slug: "dark-truths-reality-v1-pdf",
    title: "Dark Truths PDF",
    tagline: "Motivational PDFs with a harder edge.",
    summary: "Generates dark-reality and motivational PDFs — designed to feel like print, not a blog post.",
    story: [
      "Generates dark-reality and motivational PDFs — designed to feel like print, not a blog post.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["web"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/dark-truths-reality-v1-pdf",
    live: "https://dark-truths-reality-v1-pdf.vercel.app",
    cover: "planes",
  },
  {
    slug: "dental-architect-simulation-v1",
    title: "Dental Architect Simulation",
    tagline: "Plan the room before you build it.",
    summary: "A spatial simulation for dental architecture — walk a clinic layout before it exists in plaster and steel.",
    story: [
      "A spatial simulation for dental architecture — walk a clinic layout before it exists in plaster and steel.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["dental"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/dental-architect-simulation-v1",
    cover: "badge",
  },
  {
    slug: "dental-radiograph-analyser",
    title: "Dental Radiograph Analyser",
    tagline: "A second look at the film.",
    summary: "AI-assisted reading of dental radiographs. A guide, not a diagnosis — built for orientation, never as the last word.",
    story: [
      "AI-assisted reading of dental radiographs. A guide, not a diagnosis — built for orientation, never as the last word.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["dental", "ai"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/dental-radiograph-analyser",
    live: "https://dental-radiograph-analyser.vercel.app",
    cover: "rings",
  },
  {
    slug: "dev-kit",
    title: "Dev Kit",
    tagline: "One-file toolkit for makers.",
    summary: "An all-in-one toolkit for developers and creators, contained in a single page — the utilities you actually reach for.",
    story: [
      "An all-in-one toolkit for developers and creators, contained in a single page — the utilities you actually reach for.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai", "tools", "web"],
    featured: false,
    stack: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/swapagrawal14/dev-kit",
    cover: "chat",
  },
  {
    slug: "digital-static-weaver",
    title: "Digital Static Weaver",
    tagline: "Glitch, on purpose.",
    summary: "A glitch station: apply motion-static to text or an image and watch the signal fall apart, beautifully.",
    story: [
      "A glitch station: apply motion-static to text or an image and watch the signal fall apart, beautifully.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["tools"],
    featured: false,
    stack: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/swapagrawal14/digital-static-weaver",
    cover: "cube",
  },
  {
    slug: "emotion-echo-weaver",
    title: "Emotion Echo Weaver",
    tagline: "Feelings, rendered as a pattern.",
    summary: "A generative study in turning an emotional prompt into a visual echo — color, rhythm, and a little unease.",
    story: [
      "A generative study in turning an emotional prompt into a visual echo — color, rhythm, and a little unease.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["web"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/emotion-echo-weaver",
    cover: "topo",
  },
  {
    slug: "ev-arena-game",
    title: "EV Arena",
    tagline: "A free browser arena.",
    summary: "An arena game that runs in the browser — no download, no account, just play.",
    story: [
      "An arena game that runs in the browser — no download, no account, just play.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["games"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/ev-arena-game",
    cover: "film",
  },
  {
    slug: "freelance-interior-designing",
    title: "Atelier Interior AI",
    tagline: "Plan the room. Then renovate it.",
    summary: "A freelance interior tool: design and plan a workspace, then renovate it with Atelier AI.",
    story: [
      "A freelance interior tool: design and plan a workspace, then renovate it with Atelier AI.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/freelance-interior-designing",
    cover: "brackets",
  },
  {
    slug: "freelance-linkedin-dental-carousels",
    title: "Dental LinkedIn Carousels",
    tagline: "The carousel, without the chatbot detour.",
    summary: "A pipeline for LinkedIn carousels in dentistry — skip the chat-then-paste loop and go straight to slides.",
    story: [
      "A pipeline for LinkedIn carousels in dentistry — skip the chat-then-paste loop and go straight to slides.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["dental", "ai", "tools"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/freelance-linkedin-dental-carousels",
    cover: "wave",
  },
  {
    slug: "freelance-local-businesses-advertisements",
    title: "Local Business Ads",
    tagline: "Ad films for the shop down the street.",
    summary: "A freelance workflow for outstanding ad videos aimed at local businesses — brief, visuals, and a cut that can ship.",
    story: [
      "A freelance workflow for outstanding ad videos aimed at local businesses — brief, visuals, and a cut that can ship.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai", "tools"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/freelance-local-businesses-advertisements",
    cover: "orbit",
  },
  {
    slug: "funny-doodling",
    title: "Funny Doodling",
    tagline: "Draw a mess. Turn on physics.",
    summary: "Draw random shapes, make a mess, then switch physics on and watch the doodle become a little machine.",
    story: [
      "Draw random shapes, make a mess, then switch physics on and watch the doodle become a little machine.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["games"],
    featured: false,
    stack: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/swapagrawal14/funny-doodling",
    cover: "grid",
  },
  {
    slug: "gaming-meme-card-generator",
    title: "Gaming Meme Cards",
    tagline: "Trading-card memes, game-styled.",
    summary: "Compose gaming-style meme cards in the browser — a joke, framed like a collectible.",
    story: [
      "Compose gaming-style meme cards in the browser — a joke, framed like a collectible.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["tools"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/gaming-meme-card-generator",
    live: "https://gaming-meme-card-generator.vercel.app/",
    cover: "planes",
  },
  {
    slug: "gemini-co-drawing-enhanced",
    title: "Gemini Co-Drawing Enhanced",
    tagline: "Sketch with the model. Then push it.",
    summary: "An enhanced Gemini co-drawing canvas: sketch, upload, and let the model manipulate the image with you.",
    story: [
      "An enhanced Gemini co-drawing canvas: sketch, upload, and let the model manipulate the image with you.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/gemini-co-drawing-enhanced",
    live: "https://gemini-co-drawing-enhanced.vercel.app",
    cover: "badge",
  },
  {
    slug: "gemini-co-drawing-v2-0",
    title: "Gemini Co-Drawing v2",
    tagline: "The second canvas.",
    summary: "Version two of Gemini co-drawing. Needs a billed Gemini key — then the canvas becomes a conversation.",
    story: [
      "Version two of Gemini co-drawing. Needs a billed Gemini key — then the canvas becomes a conversation.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/gemini-co-drawing-v2.0",
    live: "https://gemini-co-drawing-v2-0.vercel.app",
    cover: "rings",
  },
  {
    slug: "genesis-dreamweave-forge",
    title: "Dreamweave Forge",
    tagline: "Dreams, forged into pictures.",
    summary: "A generative forge for turning a dreamlike brief into a still — atmosphere first, product second.",
    story: [
      "A generative forge for turning a dreamlike brief into a still — atmosphere first, product second.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["web"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/genesis-dreamweave-forge",
    cover: "chat",
  },
  {
    slug: "huggingf-local-inference-helper-python-script",
    title: "HF Local Inference Helper",
    tagline: "Run Hugging Face image models locally.",
    summary: "A guide and helper for deploying Hugging Face text-to-image models on a local machine — inference you can actually own.",
    story: [
      "A guide and helper for deploying Hugging Face text-to-image models on a local machine — inference you can actually own.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai", "tools"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/huggingf-local-inference-helper-python-script",
    live: "https://huggingf-local-inference-helper-pyt.vercel.app",
    cover: "cube",
  },
  {
    slug: "image-weave-creator",
    title: "Image Weave Creator",
    tagline: "Weave an image from a prompt.",
    summary: "A studio for weaving images from text — iterate, keep, and export without a desktop suite.",
    story: [
      "A studio for weaving images from text — iterate, keep, and export without a desktop suite.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["web"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/image-weave-creator",
    cover: "topo",
  },
  {
    slug: "instant-veo-studio",
    title: "Instant Veo Studio",
    tagline: "Veo, without the ceremony.",
    summary: "A thin studio around Veo-style video generation — prompt, preview, try again.",
    story: [
      "A thin studio around Veo-style video generation — prompt, preview, try again.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai", "tools"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/instant-veo-studio",
    cover: "film",
  },
  {
    slug: "motion-with-remotion",
    title: "Motion with Remotion",
    tagline: "Motion graphics, with an LLM in the chair.",
    summary: "Professional motion graphics in the browser via Remotion. Connect an API key and let any LLM help direct the piece.",
    story: [
      "Professional motion graphics in the browser via Remotion. Connect an API key and let any LLM help direct the piece.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/motion-with-remotion",
    cover: "brackets",
  },
  {
    slug: "nano-banana-image-studio",
    title: "Nano Banana Image Studio",
    tagline: "Generate and manipulate with Nano Banana.",
    summary: "An image studio built around Nano Banana — generate, edit, and keep the loop short.",
    story: [
      "An image studio built around Nano Banana — generate, edit, and keep the loop short.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai", "tools"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/Nano-Banana-Image-Studio",
    cover: "wave",
  },
  {
    slug: "random-webdev-games",
    title: "Random Webdev Games",
    tagline: "A shelf of small games.",
    summary: "A living shelf of games built across different stacks. Each new one lands here.",
    story: [
      "A living shelf of games built across different stacks. Each new one lands here.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["games", "web"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/random-webdev-games",
    cover: "orbit",
  },
  {
    slug: "reality-sketch-generator",
    title: "Reality Sketch Generator",
    tagline: "A sketch of a place that might exist.",
    summary: "Turn a prompt into a reality-styled sketch — the drawing before the photograph.",
    story: [
      "Turn a prompt into a reality-styled sketch — the drawing before the photograph.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["tools"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/reality-sketch-generator",
    cover: "grid",
  },
  {
    slug: "rubiks-cube-simulator",
    title: "Rubik's Cube Simulator",
    tagline: "A cube you can actually twist.",
    summary: "A browser Rubik's cube — twist, scramble, solve, no plugin.",
    story: [
      "A browser Rubik's cube — twist, scramble, solve, no plugin.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["games"],
    featured: false,
    stack: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/swapagrawal14/rubiks-cube-simulator",
    cover: "planes",
  },
  {
    slug: "sense-shift-alchemy",
    title: "Sense Shift Alchemy",
    tagline: "Shift one sense into another.",
    summary: "A synesthetic experiment: take a feeling, a sound, a color, and alchemize it into a different sense.",
    story: [
      "A synesthetic experiment: take a feeling, a sound, a color, and alchemize it into a different sense.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["web"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/sense-shift-alchemy",
    cover: "badge",
  },
  {
    slug: "sidi-bou-said",
    title: "Sidi Bou Said",
    tagline: "A place, as a small web study.",
    summary: "An experimental scene named for Sidi Bou Said — a location study, kept as a sketch of atmosphere.",
    story: [
      "An experimental scene named for Sidi Bou Said — a location study, kept as a sketch of atmosphere.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/sidi-bou-said",
    cover: "rings",
  },
  {
    slug: "smile-stories-v2",
    title: "Smile Stories",
    tagline: "YouTube ideas for a dental practice.",
    summary: "An AI agent that generates engaging YouTube video ideas for dental storytelling — v2 of the smile-stories line.",
    story: [
      "An AI agent that generates engaging YouTube video ideas for dental storytelling — v2 of the smile-stories line.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["dental", "ai", "tools"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/smile-stories-v2",
    cover: "chat",
  },
  {
    slug: "spark-whisper-oracle",
    title: "Spark Whisper Oracle",
    tagline: "A small oracle for a spark of a prompt.",
    summary: "An oracular prompt tool — whisper a spark, get a direction back.",
    story: [
      "An oracular prompt tool — whisper a spark, get a direction back.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/spark-whisper-oracle",
    cover: "cube",
  },
  {
    slug: "starry-ai-scribe-studio",
    title: "Starry AI Scribe",
    tagline: "Writing under a darker sky.",
    summary: "A scribe studio for AI-assisted writing — quieter than a chatbot, closer to a desk.",
    story: [
      "A scribe studio for AI-assisted writing — quieter than a chatbot, closer to a desk.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai", "tools"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/starry-ai-scribe-studio",
    cover: "topo",
  },
  {
    slug: "stickman-shooter-game",
    title: "Stickman Shooter",
    tagline: "Side-scrolling, stick-figure, fast.",
    summary: "A fast-paced side-scrolling shooter in pure HTML, CSS, and JavaScript. No engine, just the game.",
    story: [
      "A fast-paced side-scrolling shooter in pure HTML, CSS, and JavaScript. No engine, just the game.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["games", "tools", "web"],
    featured: false,
    stack: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/swapagrawal14/stickman-shooter-game",
    cover: "film",
  },
  {
    slug: "student-id-card-generator",
    title: "Student ID Card Generator",
    tagline: "A digital student ID, composed.",
    summary: "Fill in the details and export a digital student ID layout. A composition tool, not a credential.",
    story: [
      "Fill in the details and export a digital student ID layout. A composition tool, not a credential.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["dental", "ai", "tools"],
    featured: false,
    stack: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/swapagrawal14/Student-ID-Card-Generator",
    live: "https://student-id-card-generator-seven.vercel.app",
    cover: "brackets",
  },
  {
    slug: "swap-ai-models-dev",
    title: "Swap AI Models",
    tagline: "A dev bench for swapping models.",
    summary: "A development bench for talking to different AI models in one place — swap the backend, keep the thread.",
    story: [
      "A development bench for talking to different AI models in one place — swap the backend, keep the thread.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/Swap-ai-Models-dev",
    cover: "wave",
  },
  {
    slug: "swap-mail",
    title: "Swap Mail",
    tagline: "A custom temp-mail.",
    summary: "A disposable inbox you actually control — a custom temp-mail site for when you need an address, not an identity.",
    story: [
      "A disposable inbox you actually control — a custom temp-mail site for when you need an address, not an identity.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai", "web"],
    featured: false,
    stack: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/swapagrawal14/swap-mail",
    live: "https://swap-mail.vercel.app",
    cover: "orbit",
  },
  {
    slug: "swapagrawal14",
    title: "GitHub Profile",
    tagline: "The README that starts the trail.",
    summary: "The public GitHub profile README — dentist, AI researcher, builder. The index behind every repository here.",
    story: [
      "The public GitHub profile README — dentist, AI researcher, builder. The index behind every repository here.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["dental", "ai", "web"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/swapagrawal14",
    cover: "grid",
  },
  {
    slug: "system-prompts-for-sora2",
    title: "Sora 2 System Prompts",
    tagline: "A library of system prompts.",
    summary: "A collection of system prompts for Sora-class video models — drop one into a chatbot and the model arrives already briefed.",
    story: [
      "A collection of system prompts for Sora-class video models — drop one into a chatbot and the model arrives already briefed.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/System-Prompts-for-Sora2",
    cover: "planes",
  },
  {
    slug: "tale-to-picture-forge",
    title: "Tale to Picture Forge",
    tagline: "A story in. A picture out.",
    summary: "Forge an illustration from a tale — the still that should have been in the book.",
    story: [
      "Forge an illustration from a tale — the still that should have been in the book.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["3d"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/tale-to-picture-forge",
    cover: "badge",
  },
  {
    slug: "uxcopywizard",
    title: "UX Copy Wizard",
    tagline: "Interface copy, on demand.",
    summary: "A wizard for UX copy — buttons, empty states, errors — written like a product, not a slogan.",
    story: [
      "A wizard for UX copy — buttons, empty states, errors — written like a product, not a slogan.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["web"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/uxcopywizard",
    cover: "rings",
  },
  {
    slug: "visual-explainer",
    title: "Visual Explainer",
    tagline: "See the concept, not just the sentence.",
    summary: "An app that turns a concept into a visual explanation — diagrams and pictures for the things that refuse to stay in text.",
    story: [
      "An app that turns a concept into a visual explanation — diagrams and pictures for the things that refuse to stay in text.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai"],
    featured: false,
    stack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/swapagrawal14/visual-explainer",
    live: "https://visual-explainer.vercel.app",
    cover: "chat",
  },
  {
    slug: "vox-style-videos-workflow",
    title: "Vox-Style Video Workflow",
    tagline: "Explainers, with a Vox-shaped cut.",
    summary: "A complete workflow for professional Vox-style explainer videos — the guide, the prompts, and the sequence.",
    story: [
      "A complete workflow for professional Vox-style explainer videos — the guide, the prompts, and the sequence.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["ai", "tools"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/vox-style-videos-workflow",
    cover: "cube",
  },
  {
    slug: "wait-at-dent",
    title: "Waiting Room Radio",
    tagline: "Something to listen to in the chair.",
    summary: "Waiting Room Radio for patients at Dr. Swapnil Agrawal's clinic — a calm stream while you wait.",
    story: [
      "Waiting Room Radio for patients at Dr. Swapnil Agrawal's clinic — a calm stream while you wait.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["dental", "ai"],
    featured: false,
    stack: ["JavaScript", "React"],
    repo: "https://github.com/swapagrawal14/wait-at-dent",
    live: "https://wait-at-dent.vercel.app",
    cover: "topo",
  },
  {
    slug: "youtube-niche-automation",
    title: "YouTube Niche Automation",
    tagline: "Niches, automated.",
    summary: "Web apps for automating YouTube niches — from idea to a workflow you can run again.",
    story: [
      "Web apps for automating YouTube niches — from idea to a workflow you can run again.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["tools", "web"],
    featured: false,
    stack: ["Web"],
    repo: "https://github.com/swapagrawal14/youtube-niche-automation",
    cover: "film",
  },
  {
    slug: "youtube-scripts",
    title: "YouTube Scripts",
    tagline: "Workflows for people who publish.",
    summary: "A collection of workflows and scripts for YouTube creators — the unglamorous tools that make a channel ship.",
    story: [
      "A collection of workflows and scripts for YouTube creators — the unglamorous tools that make a channel ship.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["tools"],
    featured: false,
    stack: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/swapagrawal14/youtube-scripts",
    cover: "brackets",
  },
  {
    slug: "zack-d-style-animation-workflow",
    title: "Zack D Animation Workflow",
    tagline: "That film look, as a repeatable process.",
    summary: "A personal workflow for Zack D–style animation films — the steps, the prompts, and a live tool to run them.",
    story: [
      "A personal workflow for Zack D–style animation films — the steps, the prompts, and a live tool to run them.",
      "It lives on GitHub with the rest of the studio — every public repository is on these grounds.",
    ],
    tags: ["tools"],
    featured: false,
    stack: ["HTML", "CSS", "JavaScript"],
    repo: "https://github.com/swapagrawal14/zack-d-style-animation-workflow",
    live: "https://zack-d-style-animation-workflow.vercel.app",
    cover: "wave",
  },
];